// <auto-generated />
using DE1_QUANLYPHONGTRO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DE1_QUANLYPHONGTRO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DE1_QUANLYPHONGTRO.Models.RoomImage_BCS240041", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsThumbnail")
                        .HasColumnType("bit");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomImages_BCS240041");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsThumbnail = true,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsThumbnail = true,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsThumbnail = true,
                            RoomId = 3
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsThumbnail = true,
                            RoomId = 4
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsThumbnail = true,
                            RoomId = 5
                        });
                });

            modelBuilder.Entity("DE1_QUANLYPHONGTRO.Models.RoomType_BCS240041", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes_BCS240041");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Phòng dành cho 1 người",
                            Name = "Phòng Đơn"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Phòng dành cho 2 người",
                            Name = "Phòng Đôi"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Phòng rộng cho gia đình",
                            Name = "Phòng Gia Đình"
                        });
                });

            modelBuilder.Entity("DE1_QUANLYPHONGTRO.Models.Room_BCS240041", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.HasIndex("Name", "RoomTypeId")
                        .IsUnique();

                    b.ToTable("Rooms_BCS240041");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 20.0,
                            Description = "Phòng ở tầng 1",
                            IsAvailable = true,
                            Name = "Phòng 101",
                            Price = 2000000m,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Area = 25.0,
                            Description = "Phòng góc tầng 1",
                            IsAvailable = true,
                            Name = "Phòng 102",
                            Price = 2500000m,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Area = 30.0,
                            Description = "Phòng có ban công",
                            IsAvailable = true,
                            Name = "Phòng 201",
                            Price = 3000000m,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Area = 30.0,
                            Description = "Phòng mặt trước",
                            IsAvailable = false,
                            Name = "Phòng 202",
                            Price = 3000000m,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Area = 50.0,
                            Description = "Phòng gia đình rộng rãi",
                            IsAvailable = true,
                            Name = "Phòng 301",
                            Price = 5000000m,
                            RoomTypeId = 3
                        });
                });

            modelBuilder.Entity("DE1_QUANLYPHONGTRO.Models.RoomImage_BCS240041", b =>
                {
                    b.HasOne("DE1_QUANLYPHONGTRO.Models.Room_BCS240041", "Room")
                        .WithMany("RoomImages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DE1_QUANLYPHONGTRO.Models.Room_BCS240041", b =>
                {
                    b.HasOne("DE1_QUANLYPHONGTRO.Models.RoomType_BCS240041", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("DE1_QUANLYPHONGTRO.Models.RoomType_BCS240041", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DE1_QUANLYPHONGTRO.Models.Room_BCS240041", b =>
                {
                    b.Navigation("RoomImages");
                });
#pragma warning restore 612, 618
        }
    }
}
